using System.Globalization;
using System.Text;
using Microsoft.Extensions.Logging;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Kinetic.Core.Services.Export;

public class ExportService : IExportService
{
    private readonly ILogger<ExportService> _logger;

    static ExportService()
    {
        // Required for EPPlus
        ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
        // Required for QuestPDF
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public ExportService(ILogger<ExportService> logger)
    {
        _logger = logger;
    }

    public async Task<ExportResult> ExportToExcelAsync(ExportRequest request, CancellationToken cancellationToken = default)
    {
        try
        {
            using var package = new ExcelPackage();
            var worksheet = package.Workbook.Worksheets.Add(SanitizeSheetName(request.ReportName));
            var columns = request.Columns.ToList();
            var data = request.Data.ToList();
            var currentRow = 1;

            // Title
            worksheet.Cells[currentRow, 1].Value = request.ReportName;
            worksheet.Cells[currentRow, 1].Style.Font.Size = 16;
            worksheet.Cells[currentRow, 1].Style.Font.Bold = true;
            currentRow += 2;

            // Metadata
            if (request.Options.IncludeTimestamp)
            {
                worksheet.Cells[currentRow, 1].Value = "Generated:";
                worksheet.Cells[currentRow, 2].Value = DateTime.UtcNow.ToString(request.Options.DateFormat);
                currentRow++;
            }

            if (!string.IsNullOrEmpty(request.Options.GeneratedBy))
            {
                worksheet.Cells[currentRow, 1].Value = "Generated By:";
                worksheet.Cells[currentRow, 2].Value = request.Options.GeneratedBy;
                currentRow++;
            }

            // Applied filters
            if (request.Options.IncludeFilters && request.Options.AppliedFilters?.Any() == true)
            {
                currentRow++;
                worksheet.Cells[currentRow, 1].Value = "Applied Filters:";
                worksheet.Cells[currentRow, 1].Style.Font.Bold = true;
                currentRow++;
                
                foreach (var filter in request.Options.AppliedFilters)
                {
                    worksheet.Cells[currentRow, 1].Value = filter.Key;
                    worksheet.Cells[currentRow, 2].Value = filter.Value;
                    currentRow++;
                }
            }

            currentRow++; // Empty row before data

            // Headers
            var headerRow = currentRow;
            if (request.Options.IncludeHeaders)
            {
                for (var i = 0; i < columns.Count; i++)
                {
                    var cell = worksheet.Cells[currentRow, i + 1];
                    cell.Value = columns[i].DisplayName;
                    cell.Style.Font.Bold = true;
                    cell.Style.Fill.PatternType = ExcelFillStyle.Solid;
                    cell.Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.FromArgb(68, 114, 196));
                    cell.Style.Font.Color.SetColor(System.Drawing.Color.White);
                    cell.Style.Border.Bottom.Style = ExcelBorderStyle.Thin;
                }
                currentRow++;
            }

            // Data rows
            var dataStartRow = currentRow;
            foreach (var row in data)
            {
                for (var i = 0; i < columns.Count; i++)
                {
                    var column = columns[i];
                    var cell = worksheet.Cells[currentRow, i + 1];
                    
                    if (row.TryGetValue(column.Name, out var value) && value != null)
                    {
                        cell.Value = value;
                        ApplyExcelFormat(cell, column, request.Options);
                    }

                    // Alignment
                    cell.Style.HorizontalAlignment = column.Alignment switch
                    {
                        ColumnAlignment.Center => ExcelHorizontalAlignment.Center,
                        ColumnAlignment.Right => ExcelHorizontalAlignment.Right,
                        _ => ExcelHorizontalAlignment.Left
                    };
                }
                currentRow++;
            }

            // Auto-fit columns with max width
            for (var i = 0; i < columns.Count; i++)
            {
                var col = worksheet.Column(i + 1);
                col.AutoFit();
                if (col.Width > 50) col.Width = 50;
                if (columns[i].Width.HasValue) col.Width = columns[i].Width.Value;
            }

            // Freeze header row
            worksheet.View.FreezePanes(headerRow + 1, 1);

            // Add table formatting
            if (data.Any())
            {
                var tableRange = worksheet.Cells[headerRow, 1, currentRow - 1, columns.Count];
                var table = worksheet.Tables.Add(tableRange, "ReportData");
                table.TableStyle = OfficeOpenXml.Table.TableStyles.Medium2;
            }

            var bytes = await package.GetAsByteArrayAsync(cancellationToken);
            
            return new ExportResult
            {
                Success = true,
                Data = bytes,
                FileName = $"{SanitizeFileName(request.ReportName)}_{DateTime.UtcNow:yyyyMMdd_HHmmss}.xlsx",
                ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                RowCount = data.Count
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to export to Excel");
            return new ExportResult { Success = false, Error = ex.Message };
        }
    }

    public async Task<ExportResult> ExportToPdfAsync(ExportRequest request, CancellationToken cancellationToken = default)
    {
        try
        {
            var columns = request.Columns.ToList();
            var data = request.Data.ToList();
            
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(GetPageSize(request.Options.PdfPageSize));
                    if (request.Options.PdfOrientation == PdfOrientation.Landscape)
                        page.Size(GetPageSize(request.Options.PdfPageSize).Width, GetPageSize(request.Options.PdfPageSize).Height);
                    
                    page.Margin(30);
                    page.DefaultTextStyle(x => x.FontSize(10));

                    // Header
                    page.Header().Column(col =>
                    {
                        col.Item().Text(request.ReportName).FontSize(18).Bold();
                        
                        if (!string.IsNullOrEmpty(request.ReportDescription))
                            col.Item().Text(request.ReportDescription).FontSize(10).Italic();
                        
                        col.Item().PaddingTop(5).Row(row =>
                        {
                            if (request.Options.IncludeTimestamp)
                                row.AutoItem().Text($"Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm}").FontSize(8);
                            
                            if (!string.IsNullOrEmpty(request.Options.GeneratedBy))
                                row.AutoItem().PaddingLeft(20).Text($"By: {request.Options.GeneratedBy}").FontSize(8);
                        });
                        
                        col.Item().PaddingTop(10).LineHorizontal(1).LineColor(Colors.Grey.Medium);
                    });

                    // Content
                    page.Content().PaddingTop(10).Table(table =>
                    {
                        // Define columns
                        table.ColumnsDefinition(colDef =>
                        {
                            foreach (var column in columns)
                            {
                                if (column.Width.HasValue)
                                    colDef.ConstantColumn(column.Width.Value);
                                else
                                    colDef.RelativeColumn();
                            }
                        });

                        // Header row
                        table.Header(header =>
                        {
                            foreach (var column in columns)
                            {
                                header.Cell()
                                    .Background(Colors.Blue.Darken2)
                                    .Padding(5)
                                    .Text(column.DisplayName)
                                    .FontColor(Colors.White)
                                    .Bold();
                            }
                        });

                        // Data rows
                        var rowIndex = 0;
                        foreach (var row in data)
                        {
                            var bgColor = rowIndex % 2 == 0 ? Colors.White : Colors.Grey.Lighten4;
                            
                            foreach (var column in columns)
                            {
                                var value = row.TryGetValue(column.Name, out var v) ? v : null;
                                var displayValue = FormatValue(value, column, request.Options);
                                
                                table.Cell()
                                    .Background(bgColor)
                                    .Padding(4)
                                    .AlignLeft()
                                    .Text(displayValue ?? "");
                            }
                            rowIndex++;
                        }
                    });

                    // Footer
                    page.Footer().AlignCenter().Text(text =>
                    {
                        text.Span("Page ");
                        text.CurrentPageNumber();
                        text.Span(" of ");
                        text.TotalPages();
                    });
                });
            });

            using var stream = new MemoryStream();
            document.GeneratePdf(stream);
            var bytes = stream.ToArray();

            return await Task.FromResult(new ExportResult
            {
                Success = true,
                Data = bytes,
                FileName = $"{SanitizeFileName(request.ReportName)}_{DateTime.UtcNow:yyyyMMdd_HHmmss}.pdf",
                ContentType = "application/pdf",
                RowCount = data.Count
            });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to export to PDF");
            return new ExportResult { Success = false, Error = ex.Message };
        }
    }

    public Task<ExportResult> ExportToCsvAsync(ExportRequest request, CancellationToken cancellationToken = default)
    {
        try
        {
            var columns = request.Columns.ToList();
            var data = request.Data.ToList();
            var sb = new StringBuilder();

            // Headers
            if (request.Options.IncludeHeaders)
            {
                sb.AppendLine(string.Join(",", columns.Select(c => EscapeCsvField(c.DisplayName))));
            }

            // Data
            foreach (var row in data)
            {
                var values = columns.Select(col =>
                {
                    var value = row.TryGetValue(col.Name, out var v) ? v : null;
                    return EscapeCsvField(FormatValue(value, col, request.Options) ?? "");
                });
                sb.AppendLine(string.Join(",", values));
            }

            var bytes = Encoding.UTF8.GetPreamble().Concat(Encoding.UTF8.GetBytes(sb.ToString())).ToArray();

            return Task.FromResult(new ExportResult
            {
                Success = true,
                Data = bytes,
                FileName = $"{SanitizeFileName(request.ReportName)}_{DateTime.UtcNow:yyyyMMdd_HHmmss}.csv",
                ContentType = "text/csv; charset=utf-8",
                RowCount = data.Count
            });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to export to CSV");
            return Task.FromResult(new ExportResult { Success = false, Error = ex.Message });
        }
    }

    private static void ApplyExcelFormat(ExcelRange cell, ExportColumn column, ExportOptions options)
    {
        var format = column.Format?.ToLowerInvariant() ?? column.DataType.ToLowerInvariant();
        
        cell.Style.Numberformat.Format = format switch
        {
            "currency" => options.CurrencyFormat,
            "percent" => "0.00%",
            "number" or "decimal" or "int" or "integer" => options.NumberFormat,
            "date" => "yyyy-mm-dd",
            "datetime" => "yyyy-mm-dd hh:mm:ss",
            _ => "@" // Text
        };
    }

    private static string? FormatValue(object? value, ExportColumn column, ExportOptions options)
    {
        if (value == null) return null;
        
        var format = column.Format?.ToLowerInvariant() ?? column.DataType.ToLowerInvariant();
        
        return format switch
        {
            "currency" when value is decimal d => d.ToString("C", CultureInfo.CurrentCulture),
            "currency" when value is double dbl => dbl.ToString("C", CultureInfo.CurrentCulture),
            "percent" when value is decimal d => d.ToString("P2", CultureInfo.CurrentCulture),
            "percent" when value is double dbl => dbl.ToString("P2", CultureInfo.CurrentCulture),
            "date" when value is DateTime dt => dt.ToString("yyyy-MM-dd"),
            "datetime" when value is DateTime dt => dt.ToString(options.DateFormat),
            _ => value.ToString()
        };
    }

    private static string EscapeCsvField(string field)
    {
        if (field.Contains(',') || field.Contains('"') || field.Contains('\n') || field.Contains('\r'))
        {
            return $"\"{field.Replace("\"", "\"\"")}\"";
        }
        return field;
    }

    private static string SanitizeFileName(string name)
    {
        var invalid = Path.GetInvalidFileNameChars();
        return new string(name.Where(c => !invalid.Contains(c)).ToArray()).Replace(" ", "_");
    }

    private static string SanitizeSheetName(string name)
    {
        var invalid = new[] { ':', '\\', '/', '?', '*', '[', ']' };
        var result = new string(name.Where(c => !invalid.Contains(c)).ToArray());
        return result.Length > 31 ? result[..31] : result;
    }

    private static PageSize GetPageSize(PdfPageSize size) => size switch
    {
        PdfPageSize.A3 => PageSizes.A3,
        PdfPageSize.Letter => PageSizes.Letter,
        PdfPageSize.Legal => PageSizes.Legal,
        PdfPageSize.Tabloid => PageSizes.Tabloid,
        _ => PageSizes.A4
    };
}
